### PR TITLE
Buttons dataentry

### PR DESCRIPTION
**Pull request by rogercgui**
Second part of the revision completed!  
The revision will continue, because obsolete images are still stored, for example, but as there are many files changed at once I can't let the time pass too much, so as not to have conflicts with the other developments.

This review on ABCD was intended to seek a visual unity and an update in visual standards according to the current decade.

In the traditional layout, ABCD has many image files distributed within the system directories. In this work, we sought to unify as much as possible the image files in the /assets folder.

## Login Screen

The login screen was kept similar to the traditional screen, however the excess \<div> and images used to create the login box were excluded.

In this review, the login screen is made up of CSS only.

## Header

The header has been reduced to 45px high to serve as a kind of navigation bar, however it is still not possible to run completely because it conflicts with the frames in dataentry.

The header has been unified in the institutional\_info.php file, being the same file for the entire program.

In the original structure the header with the logo, modules and languages ​​were directly in the code of homepage.php, menu\_bases.php, in addition to institutional\_info.php itself. This type of situation makes maintenance difficult.

In addition to the size reduction to give more space to the rest of the system, the header gained the base selection that was removed from the position it occupied in dataentry/inicio\_main.php. The purpose of the removal was to free up some space on the toolbar when entering data. With this, in order not to be redundant, the selection has been removed from the body of the homepage.php page.

The same happened with the selection of modules and languages.

Charset and login information has been kept, however the login is only showing the user. To see the full name and database directory it is necessary to hover over the user.

Navigation between modules can now be done by button and no longer select.

The “exit” button has gained a graphic style. 

## Icons

Icons from two sources were used: FontAwesome and Microsoft Fluent UI.

Icons follow current aesthetics with linear and monochromatic symbols.

FontAwesome icons are run from a webfont that is in the /assets/webfonts directory

Fluent UI icons are in /assets/svg

Icons in SVG are useful as they are scalable. They can be reused in different dimensions without loss of quality. Unlike bitmaps.

## Colors

Despite having brought a more vivid tone to the ABCD blue, we tried to keep a more sober tone to the system. As the main objective of ABCD is to be a working tool, it avoided using too many colors and too many visual details.

3 color patterns were defined to help identify the modules.

Being:

<table><tbody><tr><td>Cataloging</td><td>#B4E1F9</td></tr><tr><td>Loan</td><td>#F7EF89</td></tr><tr><td>Acquisition</td><td>#96EAC8</td></tr></tbody></table>

The file styles.css has in the selector :root the palette used in the system. 

## Toolbars

From the data entry toolbar, toolbars emerged in the main functions of the Loans and Acquisition modules.

The reason was to keep a visual unit, since since the first version of ABCD data entry has a very different look than the rest of the system.

The toolbar is designed to have a clean look, without borders, shadows or any other unnecessary elements. Buttons are highlighted only when the mouse is over. 

## Dataentry

Dataentry has some features that make it difficult to handle. To try to reduce the difficulty a little, framesets were replaced by iframes.

Iframes are friendlier and work well with CSS. It's not the ideal solution, but due to the time it was a viable solution. It is necessary to make a more careful review of this screen to reconstruct it in a simpler way.

In addition to frames, another sore point is the use of DHTML to create the toolbar. This was maintained, but for the future it may be revised.

## Browser.php

The dataentry directory's browser.php has been changed once again. A toolbar was created to reduce some of the buttons above the table.

In languages ​​like Portuguese, the layout was very confusing. Now in the .middle div there are only the lookup resources and the table.

An important implementation of the browser is the inclusion of the “Edit User Profiles” button when in the Acces base.

This will make it easier for users to edit the system, as well as reducing clicks going back and forth to the main menu.

## Future

Still need to standardize secondary screens, back buttons and databases.

During this work I noticed that the bases in the Windows and Linux versions are very different, at least in the Portuguese language. 

So the work goes on!

### CODE REVIEW

**Comment by fho4abcd** [comment]
This is a significant update. Visually and in the number of touched files.
First impression is very good !!

**Comment by edsz14** [comment]
For sure this needs some adjusting to the user as indeed so many things have changed. Not saying this is bad, but we need to check - after some 'getting used' to it - also the details before releasing this. E.g. : 
- the acquisitions module is represented by a 'shopping basket' icon, one can see the link but still not obvious 
- the 'Select' on top of the screen should make it clear that it is about 'database selected', at first I had not even noted it...
- the icon for 'search' in the data-entry toolbar, esp. with the 'i' in the magnifying glass, rather suggests 'information' than 'search'; the 'free search' icon (the magnifying glass without 'i') maybe should be moved to the search window itself as a sub-option of search.
Other changes, like moving the detailed info about the logged in operator to the 'hover info', are very nice indeed.
     On Friday, September 24, 2021, 10:49:26 AM GMT+2, Fred ***@***.***> wrote:  
 
 


This is a significant update. Visually and in the number of touched files.
First impression is very good !!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fho4abcd** [comment]
I have merged this in order to have the big change first and to speak about the same platform. Minor changes I see:
- Agree with Egbert on the Select, no opinion on the other remarks (have to get used to it first)
- Several "standard" buttons changed from purple to grey. Now the text is hard to read
image
- More to follow...

**Comment by rogercgui** [comment]
Hello Fred and Egbert!

Responding to your remarks:  
\- Choosing icons to represent a function is a difficult task! For some like Acquisition I consulted colleagues that perform the function and researched the other softwares. Folio (https://wiki.folio.org/) being the newest software in development helped me to define the symbols:



\- The selection at the top requires a revision in the translations, at this first moment I concentrated the work in the htdocs folder, I avoided modifications in the "bases" directory. (I'll update soon)

\- The search icon didn't please me, probably I'll have to redesign some icons for not finding any better solution in the Microsoft table.

\- The gray lettering on some inputs was a CSS stumble that I will also fix in the next submission (today).

**Comment by fho4abcd** [comment]
Yes, fully agree that choosing icons and colours is a very difficult task. Take your time for the next submission. Gives us time to get used to this new look...

**Pull request merged**
