### PR TITLE
Branch to delete phantom data in examples

### PR DESCRIPTION
**Pull request by fho4abcd**

### CODE REVIEW

**Comment by edsz14** [comment]
What are 'phantom' par- and def-files ? Those belonging to non-standard databases ? The problem is that we never defined which databases are 'standard', I think most will agree MARC is one of them, but what with MARCUNI (the UTF8 variant), RDA and the many databases of non-library use (e.g. experts, events, classrooms...) ? They illustrate indeed the richness and flexibility of ABCD.
If 'phantom' means 'unused' : how do we define 'used or unused' ? My opinion : since these are very small files and don't do any harm if there - as examples, to be edited/checked/managed by system managers, I would rather keep them. Indeed also as a reminder to system-managers : look how much more you can do with ABCD than just a traditional library system with books, OPAC and circulation. 
Probably the actual definition of 'non-standard' or 'unused' is : there are no real database files (folders) for those .par and .def. That could be correct, since I dropped tons of databases from my own local installation for the distribution package, and the Git-repo was built on a previous distribution. But the difference is this : in the par-folder they hardly take space, while as real databases they would blow up the whole package. 
If we prefer a cleaner installation with only .par and .def files for real databases, maybe we should review that list again, which is lower priority anyway.     On Tuesday, November 16, 2021, 04:16:17 PM GMT+1, Fred ***@***.***> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/ABCD-DEVCOM/ABCD2/pull/221

Commit Summary
   
   - c353b26 Cleanup dubcorebiguni
   - 00cc71a Remove unused .par files (windows-examples)
   - 4709480 remove phantom .par files (examples_Linux)

File Changes 
 
(62 files)
   
   -  D www/bases-examples_Linux/par/AAUTEST.def (3) 
   -  D www/bases-examples_Linux/par/AGRIS.def (32) 
   -  D www/bases-examples_Linux/par/ASFA.def (31) 
   -  D www/bases-examples_Linux/par/BINONUNI.def (30) 
   -  D www/bases-examples_Linux/par/DBSECS.def (27) 
   -  D www/bases-examples_Linux/par/DOAJ.def (30) 
   -  D www/bases-examples_Linux/par/DOAR.def (31) 
   -  D www/bases-examples_Linux/par/EQUIPMENT.def (25) 
   -  D www/bases-examples_Linux/par/NONUNICODE.def (31) 
   -  D www/bases-examples_Linux/par/aautest.par (4) 
   -  D www/bases-examples_Linux/par/admarc.pft (184) 
   -  D www/bases-examples_Linux/par/agris.par (4) 
   -  D www/bases-examples_Linux/par/asfa.par (4) 
   -  D www/bases-examples_Linux/par/baker.par (4) 
   -  D www/bases-examples_Linux/par/binonuni.par (7) 
   -  D www/bases-examples_Linux/par/digili2.par (7) 
   -  D www/bases-examples_Linux/par/doaj.par (4) 
   -  D www/bases-examples_Linux/par/doar.par (4) 
   -  D www/bases-examples_Linux/par/nonunicode.par (4) 
   -  D www/bases-examples_Linux/par/reserva.par (7) 
   -  D www/bases-examples_Linux/par/reservaasoisis.par (4) 
   -  D www/bases-examples_Linux/par/sclib.par (9) 
   -  D www/bases-examples_Linux/par/statistics.par (12) 
   -  D www/bases-examples_Windows/dubcorebiguni/collection/documentation/progit__221359.pdf (0) 
   -  D www/bases-examples_Windows/dubcorebiguni/collection/various/አስመጣ።__211111221451.docx (0) 
   -  D www/bases-examples_Windows/dubcorebiguni/data/fullinv.bat (1) 
   -  D www/bases-examples_Windows/par/AAUTEST.def (3) 
   -  D www/bases-examples_Windows/par/AGRIS.def (32) 
   -  D www/bases-examples_Windows/par/ASFA.def (31) 
   -  D www/bases-examples_Windows/par/BINONUNI.def (30) 
   -  D www/bases-examples_Windows/par/DBSECS.def (27) 
   -  D www/bases-examples_Windows/par/DIGLIB.def (34) 
   -  D www/bases-examples_Windows/par/DISCOVERY.def (30) 
   -  D www/bases-examples_Windows/par/DOAJUNI.def (31) 
   -  D www/bases-examples_Windows/par/DOAR.def (31) 
   -  D www/bases-examples_Windows/par/EQUIPMENT.def (25) 
   -  D www/bases-examples_Windows/par/RESEARCHEVENT.def (30) 
   -  D www/bases-examples_Windows/par/RESEARCHEXPERT.def (30) 
   -  D www/bases-examples_Windows/par/RESEARCHINSTITUTES.def (30) 
   -  D www/bases-examples_Windows/par/RESEARCHLIBRARYNETWORK.def (59) 
   -  D www/bases-examples_Windows/par/RESEARCHPROJECT.def (31) 
   -  D www/bases-examples_Windows/par/SOFTWARE.def (32) 
   -  D www/bases-examples_Windows/par/aautest.par (4) 
   -  D www/bases-examples_Windows/par/admarc.pft (184) 
   -  D www/bases-examples_Windows/par/agris.par (4) 
   -  D www/bases-examples_Windows/par/asfa.par (4) 
   -  D www/bases-examples_Windows/par/baker.par (4) 
   -  D www/bases-examples_Windows/par/binonuni.par (7) 
   -  D www/bases-examples_Windows/par/digili2.par (7) 
   -  D www/bases-examples_Windows/par/diglib.par (4) 
   -  D www/bases-examples_Windows/par/discovery.par (4) 
   -  D www/bases-examples_Windows/par/doajuni.par (4) 
   -  D www/bases-examples_Windows/par/doar.par (4) 
   -  D www/bases-examples_Windows/par/researchevent.par (7) 
   -  D www/bases-examples_Windows/par/researchexpert.par (7) 
   -  D www/bases-examples_Windows/par/researchinstitutes.par (4) 
   -  D www/bases-examples_Windows/par/researchlibrarynetwork.par (9) 
   -  D www/bases-examples_Windows/par/researchproject.par (5) 
   -  D www/bases-examples_Windows/par/reserva.par (7) 
   -  D www/bases-examples_Windows/par/reservaasoisis.par (4) 
   -  D www/bases-examples_Windows/par/software.par (4) 
   -  D www/bases-examples_Windows/par/statistics.par (12) 

Patch Links:
   
   - https://github.com/ABCD-DEVCOM/ABCD2/pull/221.patch
   - https://github.com/ABCD-DEVCOM/ABCD2/pull/221.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogercgui** [comment]
Egbert,

I think that these files that are not linked to any existing base or are not called by any file can be deleted for the following reasons:  
\- It obscures the view of those who are looking for a specific file, especially when the files have very similar names;  
\- they reduce the compression and decompression time of the package. Several 1kb files, for example, take as much time as two 100mb files;  
\- maintaining 2 directories of databases (windows and linux) is already hard work for us, I think that the more we cut down what is unnecessary, the better.

About the standard databases, I think it could be reviewed what should be offered to the community. Databases like Experts could be in the repository as an add-on and not part of the distribution package.

In my opinion I would leave the basics for the functioning of ABCD as library, museum and archive software. Not so popular standards could be made available for optional installation.

Idea thinking about us who have to deal with so many files.

**Comment by edsz14** [comment]
OK, let me ponder a while about the idea to limit the number of demo-databases and add others into an extra folder into the repo. Limiting the demo-databases to the classic library ones (MARC, COPIES, LOANOBJECTS, TRANS, RESERVE, USERS) in my view is incorrectly representing the power of ABCD as a Swiss-knife not only for library management. That remains my strong opinion, I know it goes against the horribly traditional culture of librarians, but if that is the way to go I will gladly say 'farewell' to ABCD (and make my wife happy). 
OK, this sounds harsh, but I haven't worked most of my career in defending exactly that idea of widening up the scope of 'modern libraries' by promoting ABCD as a Swiss knife tool for information management - otherwise I could have gone for KOHA and have had much more success..! 
By the way, also the dubcore full-text database - on which both Fred and myself have spent most time - would need to remain despite not fitting fully in that traditional setup. 
So it will be key to carefully select a subset of demo-databases and then make the distribution also consistent in that regard. I admit having been sloppy in that set of databases as it is now : it just reflects (most of) my local ABCD setup without having given it sufficient thought. We can/should do that still, agreed. 
In my view we can do this as soon as the scripts (the 'software' therefore) are ready for distribution. In reality the users downloading the distribution all will have different subsets of databases anyway and - again in my view - need to know anyhow how to set up a database, with or without a model being available already.     On Tuesday, November 16, 2021, 08:54:30 PM GMT+1, Roger C Guilherme ***@***.***> wrote:  
 
 


Egbert,

I think that these files that are not linked to any existing base or are not called by any file can be deleted for the following reasons:
- It obscures the view of those who are looking for a specific file, especially when the files have very similar names;
- they reduce the compression and decompression time of the package. Several 1kb files, for example, take as much time as two 100mb files;
- maintaining 2 directories of databases (windows and linux) is already hard work for us, I think that the more we cut down what is unnecessary, the better.

About the standard databases, I think it could be reviewed what should be offered to the community. Databases like Experts could be in the repository as an add-on and not part of the distribution package.

In my opinion I would leave the basics for the functioning of ABCD as library, museum and archive software. Not so popular standards could be made available for optional installation.

Idea thinking about us who have to deal with so many files.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogercgui** [comment]
Okay! My bad idea!  
The essence of ABCD is to be multiple with infinite possibilities.

I was only thinking about the amount of files that need to be edited and not the whole.

**Pull request merged**
