### PR TITLE
Review of the configuration screen

### PR DESCRIPTION
**Pull request by rogercgui**
In this version more options were made available to the user.  
Some options that were fixed in config.php now appear as options in the interface.  
These options are:  
Save log;  
Default language;  
Date format;  
Open in a new window;  
Password change option;

Also included is a working database option. An old demand from those who work with only one database. By selecting a fixed database, there is no need to select the database each time you return to the main screen.

The treatment of uploads is not yet concluded, but the uploads folder has been moved to the root of htdocs to facilitate permissions control.

A help was included beside each field, since this is a sensitive area of the system, it is important to make clear the function of each field.

### CODE REVIEW

**Comment by edsz14** [comment]
Using a folder in htdocs for uploads in fact means 'back to the past' since it used to be that way, but was changed for a (good ?) reason, i.e. the htdocs-folder not being writable for outsiders. So how does this affect access rights of the files in the file-system ? In Linux I always put htdocs at 755 and bases at 777, a clear distinction which now is no more there. Also for backing up files it becomes more complicated : files in htdocs have a different backup need (periodicity) from the files in bases. Let's think over this carefully. 
At least I hope the folder in htdocs is not called 'bases' as that would again create confusion. Don't forget there is also still the symbolic link 'bases' in www. 


     On Sunday, January 30, 2022, 04:46:08 AM GMT+1, Roger C Guilherme ***@***.***> wrote:  
 
 
In this version more options were made available to the user.
Some options that were fixed in config.php now appear as options in the interface.
These options are:
Save log;
Default language;
Date format;
Open in a new window;
Password change option;

Also included is a working database option. An old demand from those who work with only one database. By selecting a fixed database, there is no need to select the database each time you return to the main screen.

The treatment of uploads is not yet concluded, but the uploads folder has been moved to the root of htdocs to facilitate permissions control.

A help was included beside each field, since this is a sensitive area of the system, it is important to make clear the function of each field.

You can view, comment on, or merge this pull request online at:

  https://github.com/ABCD-DEVCOM/ABCD2/pull/296

Commit Summary
   
   - 2188e80 Review of the configuration screen

File Changes 
 
(18 files)
   
   -  M www/bases-examples_Linux/abcd.def (13) 
   -  M www/htdocs/assets/css/colors.css (2) 
   -  M www/htdocs/assets/css/styles.css (45) 
   -  M www/htdocs/central/common/footer.php (33) 
   -  M www/htdocs/central/common/header.php (2) 
   -  M www/htdocs/central/common/header_display.php (20) 
   -  M www/htdocs/central/common/homepage.php (2) 
   -  M www/htdocs/central/common/institutional_info.php (90) 
   -  M www/htdocs/central/config.php (88) 
   -  D www/htdocs/central/dbadmin/conf_abcd.php (109) 
   -  D www/htdocs/central/dbadmin/databases_list.php (114) 
   -  D www/htdocs/central/dbadmin/editar_abcd_def.php (344) 
   -  D www/htdocs/central/dbadmin/editar_abcd_def_inc.php (240) 
   -  D www/htdocs/central/dbadmin/editar_correo_ini.php (123) 
   -  M www/htdocs/central/dbadmin/menu_modificardb.php (4) 
   -  M www/htdocs/central/lang/00/dbadmin.tab (1042) 
   -  M www/htdocs/central/settings/editar_abcd_def.php (399) 
   -  M www/htdocs/index.php (8) 

Patch Links:
   
   - https://github.com/ABCD-DEVCOM/ABCD2/pull/296.patch
   - https://github.com/ABCD-DEVCOM/ABCD2/pull/296.diff

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogercgui** [comment]
Egbert, como comentei no commit. Não concluí a parte do upload e como foi muito trabalho até agora refazer o editar\_abcd\_def e editar muitos arquivos, resolvi enviar para não me atrapalhar.

Quando o Fred faz muitos commits e eu estou trabalhando, às vezes, se eu não presto atenção ao desenvolvimento aparecem problemas inconvenientes.

Acredito que até amanhã eu conclua esta parte do upload especificamente.

A solução final vai agradar a todos, acredito.

**Comment by edsz14** [comment]
OK, no problema.

     On Sunday, January 30, 2022, 12:03:15 PM GMT+1, Roger C Guilherme ***@***.***> wrote:  
 
 


Egbert, como comentei no commit. Não concluí a parte do upload e como foi muito trabalho até agora refazer o editar_abcd_def e editar muitos arquivos, resolvi enviar para não me atrapalhar.

Quando o Fred faz muitos commits e eu estou trabalhando, às vezes, se eu não presto atenção ao desenvolvimento aparecem problemas inconvenientes.

Acredito que até amanhã eu conclua esta parte do upload especificamente.

A solução final vai agradar a todos, acredito.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rogercgui** [comment]
Now that I saw that I answered in Portuguese, sorry.

**Pull request merged**
