### PR TITLE
fixed errors in browser.php

### PR DESCRIPTION
**Pull request by rogercgui**
fixed, but there is still a lot of work to do on this browser.

### CODE REVIEW

**Comment by fho4abcd** [comment]
Right, a nasty problem, but it is better and usable now. Did not test the Expression. What I see is:
- Show deleted records works on the first page. Uncheck gives only active records (=OK). After Click Next/Last the toggle is checked (should be remembered). Uncheck shows page 1 (should be the current page)
- Search with more then 10 result records: The first page is 10 (=OK) the next page shows all remaining entries (should be paged too). Uncheck show deleted records modifies the search term (in my case "%2522AUTHOR%2522") gives 0 results (=wrong) and error message "_Notice: Undefined variable: display_total in C:\var\www\abcd22\www\htdocs\central\dataentry\browse.php on line 539_"

**Comment by rogercgui** [comment]
Hi, Fred.I noticed these errors and furthermore noticed that the "prefixes" don't work in the search either.   
I opted to fix and leave functional this original "2009-12-03" file, but as I mentioned before I'm working on a new "browse.php" with more features.

I believe that in another week I can submit the new version.

**Comment by fho4abcd** [comment]
OK. Thanks in advance and take care. Great that you understand the wxis files (for me a bridge too far)

**Comment by rogercgui** [comment]
Hi, I'm working carefully, I even made a map of the fields used in the system to maintain the standard, but I realized that some files escape the standard.   
Other files I did not locate the use.

See the spreadsheet: https://docs.google.com/spreadsheets/d/1AAEO-lPkKW6KsB75jz2osa3YBR5LIH2cUJwS7noO29w/edit?usp=sharing

**Comment by edsz14** [comment]
This list could be very useful work, depending on how consistent these field tags remain.     On Wednesday, July 7, 2021, 06:16:42 AM GMT+2, Roger C Guilherme ***@***.***> wrote:  
 
 


Hi, I'm working carefully, I even made a map of the fields used in the system to maintain the standard, but I realized that some files escape the standard. 
Other files I did not locate the use.

See the spreadsheet: https://docs.google.com/spreadsheets/d/1AAEO-lPkKW6KsB75jz2osa3YBR5LIH2cUJwS7noO29w/edit?usp=sharing

**Comment by fho4abcd** [comment]
Interesting information. My perception was that these wxis tags were predefined somewhere. I am still looking for document WWWISIS-IsisScript-en.pdf (ISIS Script Language reference ). May that can shine a light

**Comment by rogercgui** [comment]
I have this document. I believe it was in a LILDBI-WEB manual. I taught a class on it years ago, but I don't know where I kept the material. I'll look for it and as soon as I send it, I'll share it.

**Comment by rogercgui** [comment]
I found the manual in Portuguese. It was from iAH, not LILDBI-WEB. See page 73. https://drive.google.com/file/d/18a_6iwvcZQcdDN5TUYR180pU2A5ljvTB/view?usp=sharing

**Pull request merged**
