### PR TITLE
Visual corrections in browser.php

### PR DESCRIPTION
**Pull request by rogercgui**
- Creation of a function to correct the footer of the grid;
- Correction of the direction of the arrow in the option "Last";
- Closing of HTML attributes that were open.

### CODE REVIEW

**Comment by fho4abcd** [comment]
The bottom bar looks nice.

- One of the code modifications causes a new error.Happens on windows and linux. Steps to reproduce:  Create (new user), Fill the required fields, Save record. Results in "WXIS|execution error|format syntax|Invalid operand class | " and no new user is created.
- The pagination (20 entries/page as seen in the code) does not work. This was not working in the original version and does not work in the new version. May be you can look at this too.

**Comment by rogercgui** [comment]
Thanks for checking it out. I have made simple changes, I will look more thoroughly at this file.

**Comment by fho4abcd** [comment]
The bottom bar looks nice.

- One of the code modifications causes a new error.Happens on windows and linux. Steps to reproduce:  Create (new user), Fill the required fields, Save record. Results in "WXIS|execution error|format syntax|Invalid operand class | " and no new user is created.
- The pagination (20 entries/page as seen in the code) does not work. This was not working in the original version and does not work in the new version. May be you can look at this too.
- The search option did not work and does not work
- Just checked my 1.4 installation: It has pages of **10** entries. Pagination works: click on First/Previous/Next/Last shows the correct page and no alert (=better IMHO)

**Comment by rogercgui** [comment]
I have spent the weekend working on the browse.php file, I believe it will be ready for submission soon.
I encountered several problems:
- leer_mfnrange.xis not sending the registration status. This prevents knowing the status of the record, so a blocked or deleted record shows up as active. - Fixed!
- the value for "showdeleted" is "yes" and not "y" as it appears in the script - Fixed!
- error starts in script "/dbadmin/users_adm.php" - Fixed!
- The option to show deleted comes by default checked, but when unchecked the sum of records remains the same, this happens because there is a missing function to sum the deleted - I'm working on it.

As soon as I finish all the correction I will submit the 3 files involved.

Translated with www.DeepL.com/Translator (free version)

**Pull request closed without merging**
