### PR TITLE
new look - p1

### PR DESCRIPTION
**Pull request by rogercgui**
Dear Friends,
I am working hard on reorganising the ABCD layout. With that, I'm taking the opportunity to implement some graphical changes.

With the inclusion of Font Awesome in the Browser it was easier to create buttons and replace some icons that look like Windows Vista (nothing against it, but its time has passed).

The work is far from being concluded. There are many css, images and JS files scattered around the program.

My intention is to unify everything in the /assets directory. 

Since I moved a lot of files, I decided to do a commit before continuing.

It was moved 415 files, but most of them only had changes in the images path.

Some files in the /acquisitions folder were corrected.

The /central/images folder was moved to /assets/images, as well as the css files.

I made a big modification in /dbadmin/menu_mantenimiento.php, I included an iframe to load the navbar scripts. The iframe automatically adjusts itself to the loaded file.

In the next updates I intend to move the folders:
/central/imgs
/central/dataentry/img
/central/dataentry/js

Best regards!

### CODE REVIEW

**Comment by fho4abcd** [comment]
My comment:
- Fully agree with the intention to concentrate in assets, unify many things and more modern icons. This is a lot of work but it will pay itself back sometime
- My opinion is that there is still too much white space. The screens need more scrolling as in the old situation.
- The background color of the footer is now white. In this way it looks to me as an extension of the working space There is a small gray space separating the form content from the footer so others may see that differently
- The iframe in menu_mantienemento is in my opinion not an improvement:
  - All called scripts have code to display the institutional info,, a breadcrumb, a helper and a footer. Only the helper shows up now and the other info disappears. 
  - Several of these scripts are also used in dataentry_administrar where they are displayed in an iframe with complete different characteristics. This implied special code to show/not show the institutional info. The breadcrumb and footer are functional in that frame. That frame is part of a frameset (framesets will become obsolete in the next html, so that is not the way to proceed).
  - There is a significant white space between the page content and the displayed footer (from menu_mantienemento). Some testing revealed that this was caused by the footer in the code of the scripts called by menu_mantienemento. If the footer is removed from the script we get scrollbars (which is also not desired)
image
 - My opinion is that this pull request, despite the remarks above, should be honoured as this overall the way to go

**Comment by rogercgui** [comment]
Hello, Fred.  
It is being a challenge to maintain the ABCD identity while bringing in more current elements.  
This commit was the first step.   
I agree with your observations and will adjust them.

About the iframe, after doing it I thought I could have solved it by embedding the menu in all those pages.

From the beginning I think ABCD has a lot of go and back actions that could be solved with persistent menus. Example: the User Administration, which there are 2 links to Profiles and Users. That step in my opinion could be a single screen.

I will continue developing this work and submitting it to you to give your opinions.

I will review the use of the iframe to find a better solution.

I believe that 13 years later, ABCD needs to bring a graphical novelty as well, besides all the technical implementations already made.

Thanks for your feedback!

**Comment by fho4abcd** [comment]
Hi Roger
And I will merge your pull request.

And these go and back options: agree that it is sometimes very userunfriendly.
The User administration is indeed such an example. But also the menu_mantienemento in the old version. Your new version has at least the advantage that the backbutton (which is now invisible) computed by the called scripts is not necessary.

About embedding that menu: The scripts used " /central/dataentry/administrar.php " know that they do not have to display the institutional info by variable $iframe. May be you could use that trick also for not displaying the menu of menu_mantienemento. 
Thanks for all your work

**Comment by fho4abcd** [comment]
Something wrong with the Utilities menu.
The webdeveloper gives on windows:
image
and on linux:
image

**Comment by rogercgui** [comment]
I will send in the next few hours the correction of this and a few other things I found.

I believe it will fix it. I'm testing it further.

**Pull request merged**
