### PR TITLE
Worksheet without images

### PR DESCRIPTION
**Pull request by rogercgui**
For correct operation it is necessary to merge the other pull requests.

### CODE REVIEW

**Comment by rogercgui** [comment]
Hello, Fred.   
\- I will update my version to get synced correctly.

\- Some problems must have occurred due to the work being done on two computers, something must have gone unnoticed by me of the file versions.

\- About the icons, there are only limits when we use the company's CDN, in this case we are hosting in our own application. On Font Awesome's Github there is a similar issue FortAwesome/vue-fontawesome#220

\- About the colours: the Free version does not support colours in Webfonts, but the SVG can be colored. I haven't uploaded SVG files to the server yet because my goal right now is to clean up excess code and files. I believe that adding SVGs to include more colours is feasible.

\- About the conflict in styles.css, I'll fix it soon. I'll compare the files and send.

**Comment by rogercgui** [comment]
I forgot to comment:  
\- About the new layout, I am studying the possibility of using Microsoft's Fluent UI (https://developer.microsoft.com/en-us/fluentui#/) taking advantage that ABCD has a lot of the Windows Vista look, I think it will look nice with this Microsoft aesthetic.

\- I intend to use these icons in the main screens: https://developer.microsoft.com/en-us/fluentui#/styles/web/icons and keep Font Awesome in the toolbars.

But as I said, I am studying. My intention is to clean the excess of code and files scattered around the system to start building the final look for this version.

**Comment by fho4abcd** [comment]
Thanks for your quick answer (that is a relief) and your plans. I think we can close this request now as new ones will come to override this one

**Comment by fho4abcd** [comment]
The merge of your branch master makes much better. Thanks
I have only one strange thing left. In dataentry/scripts_dataentry.php the image reference **../images**. This was after https://github.com/ABCD-DEVCOM/ABCD2/commit/6b15da411a0b52ec637d6641b6189be2450a5cf0 (new look p1) **../../assets/images**. I assume that **../images** is wrong Correct?

**Pull request merged**
